### ISSUE TITLE
Make hotkeys-js a dep

### ISSUE THREAD

**Issue by ghostdevv** [PuruVJ/svelte-hotkeys#1]
It would be great to make `hotkeys-js` a dependency instead of a peer dependency, npm 7 should install peer dependencies by default but for those of us still on 6 it's one less error to potentially have to troubleshoot.

**Comment by PuruVJ** [comment]
Hmm. Seems like a good idea, I will consider that

(BTW, are you using this library? It's just a side experiment that I made for fun and then abandoned. If people are using it, I might as well start maintaining it 🤣🤣.

**Comment by ghostdevv** [comment]
@PuruVJ I just started using it today for a project I am working on, it is awesome

**Comment by PuruVJ** [comment]
Thank you!!

Just one heads up, pls don't apply this action on anything other than `<svelte:window />`, otherwise it runs the event handler twice, which is a bug I haven't been able to solve.

Happy svelting! 😁
